library(ROCR)

optRoc.cut = function(perf, pred){
  cut.ind = mapply(FUN=function(x, y, p){
    d = x^2 + (y-1)^2
    ind = which(d == min(d))
    c(sensitivity = y[[ind]], specificity = 1-x[[ind]], 
      cutoff = p[[ind]])
  }, perf@x.values, perf@y.values, pred@cutoffs)
}

setwd("/Users/ettore/git/SurvivalFactorization/resources/datasets/twitter3/preds/s2bis")

zRoc = "#topics\tsensitivity\tspecificity\tcutoff"
zF = "#topics\tF1-Measure\tcutoff"

s <- rep("",8)
aucs <- rep("",8)

data <- read.csv(file = "twitter3_s2bis_2f.pred",sep="\t")
pred <- prediction(data$Prediction,data$Class)
fm1 <- performance(pred,"f")
bestAccInd <- which.max(fm1@"y.values"[[1]])
zF = paste(zF, paste("2", fm1@"y.values"[[1]][bestAccInd], fm1@"x.values"[[1]][bestAccInd], sep = "\t"), sep = "\r\n")
precrec1 <- performance(pred,"prec", "rec")
roc1 <- performance(pred,"tpr","fpr")
auc1 <- performance(pred,"auc")
aucs[1] = paste("Twitter 2 Topics (AUC = ",sprintf("%.3f",auc1@y.values),")", sep = "")
cut <- optRoc.cut(roc1, pred)
zRoc = paste(zRoc, paste("2", cut[1,1], cut[2,1], cut[3,1], sep = "\t"), sep = "\r\n")
s[1] = paste("Twitter 2 Topics")


data <- read.csv(file = "twitter3_s2bis_4f.pred",sep="\t")
pred <- prediction(data$Prediction,data$Class)
fm2 <- performance(pred,"f")
bestAccInd <- which.max(fm2@"y.values"[[1]])
zF = paste(zF, paste("4", fm2@"y.values"[[1]][bestAccInd], fm2@"x.values"[[1]][bestAccInd], sep = "\t"), sep = "\r\n")
precrec2 <- performance(pred,"prec", "rec")
roc2 <- performance(pred,"tpr","fpr")
auc2 <- performance(pred,"auc")
aucs[2] = paste("Twitter 4 Topics (AUC = ",sprintf("%.3f",auc2@y.values),")", sep = "")
cut <- optRoc.cut(roc2, pred)
zRoc = paste(zRoc, paste("4", cut[1,1], cut[2,1], cut[3,1], sep = "\t"), sep = "\r\n")
s[2] = paste("Twitter 4 Topics")


data <- read.csv(file = "twitter3_s2bis_8f.pred",sep="\t")
pred <- prediction(data$Prediction,data$Class)
fm3 <- performance(pred,"f")
bestAccInd <- which.max(fm3@"y.values"[[1]])
zF = paste(zF, paste("8", fm3@"y.values"[[1]][bestAccInd], fm3@"x.values"[[1]][bestAccInd], sep = "\t"), sep = "\r\n")
precrec3 <- performance(pred,"prec", "rec")
roc3 <- performance(pred,"tpr","fpr")
auc3 <- performance(pred,"auc")
aucs[3] = paste("Twitter 8 Topics (AUC = ",sprintf("%.3f",auc3@y.values),")", sep = "")
cut <- optRoc.cut(roc3, pred)
zRoc = paste(zRoc, paste("8", cut[1,1], cut[2,1], cut[3,1], sep = "\t"), sep = "\r\n")
s[3] = paste("Twitter 8 Topics")


data <- read.csv(file = "twitter3_s2bis_16f.pred",sep="\t")
pred <- prediction(data$Prediction,data$Class)
fm4 <- performance(pred,"f")
bestAccInd <- which.max(fm4@"y.values"[[1]])
zF = paste(zF, paste("16", fm4@"y.values"[[1]][bestAccInd], fm4@"x.values"[[1]][bestAccInd], sep = "\t"), sep = "\r\n")
precrec4 <- performance(pred,"prec", "rec")
roc4 <- performance(pred,"tpr","fpr")
auc4 <- performance(pred,"auc")
aucs[4] = paste("Twitter 16 Topics (AUC = ",sprintf("%.3f",auc4@y.values),")", sep = "")
cut <- optRoc.cut(roc4, pred)
zRoc = paste(zRoc, paste("16", cut[1,1], cut[2,1], cut[3,1], sep = "\t"), sep = "\r\n")
s[4] = paste("Twitter 16 Topics")


data <- read.csv(file = "twitter3_s2bis_32f.pred",sep="\t")
pred <- prediction(data$Prediction,data$Class)
fm5 <- performance(pred,"f")
bestAccInd <- which.max(fm5@"y.values"[[1]])
zF = paste(zF, paste("32", fm5@"y.values"[[1]][bestAccInd], fm5@"x.values"[[1]][bestAccInd], sep = "\t"), sep = "\r\n")
precrec5 <- performance(pred,"prec", "rec")
roc5 <- performance(pred,"tpr","fpr")
auc5 <- performance(pred,"auc")
aucs[5] = paste("Twitter 32 Topics (AUC = ",sprintf("%.3f",auc5@y.values),")", sep = "")
cut <- optRoc.cut(roc5, pred)
zRoc = paste(zRoc, paste("32", cut[1,1], cut[2,1], cut[3,1], sep = "\t"), sep = "\r\n")
s[5] = paste("Twitter 32 Topics")


data <- read.csv(file = "twitter3_s2bis_64f.pred",sep="\t")
pred <- prediction(data$Prediction,data$Class)
fm6 <- performance(pred,"f")
bestAccInd <- which.max(fm6@"y.values"[[1]])
zF = paste(zF, paste("64", fm6@"y.values"[[1]][bestAccInd], fm6@"x.values"[[1]][bestAccInd], sep = "\t"), sep = "\r\n")
precrec6 <- performance(pred,"prec", "rec")
roc6 <- performance(pred,"tpr","fpr")
auc6 <- performance(pred,"auc")
aucs[6] = paste("Twitter 64 Topics (AUC = ",sprintf("%.3f",auc6@y.values),")", sep = "")
cut <- optRoc.cut(roc6, pred)
zRoc = paste(zRoc, paste("64", cut[1,1], cut[2,1], cut[3,1], sep = "\t"), sep = "\r\n")
s[6] = paste("Twitter 64 Topics")


data <- read.csv(file = "twitter3_s2bis_128f.pred",sep="\t")
pred <- prediction(data$Prediction,data$Class)
fm7 <- performance(pred,"f")
bestAccInd <- which.max(fm7@"y.values"[[1]])
zF = paste(zF, paste("128", fm7@"y.values"[[1]][bestAccInd], fm7@"x.values"[[1]][bestAccInd], sep = "\t"), sep = "\r\n")
precrec7 <- performance(pred,"prec", "rec")
roc7 <- performance(pred,"tpr","fpr")
auc7 <- performance(pred,"auc")
aucs[7] = paste("Twitter 128 Topics (AUC = ",sprintf("%.3f",auc7@y.values),")", sep = "")
cut <- optRoc.cut(roc7, pred)
zRoc = paste(zRoc, paste("128", cut[1,1], cut[2,1], cut[3,1], sep = "\t"), sep = "\r\n")
s[7] = paste("Twitter 128 Topics")

data <- read.csv(file = "links.remapped_reduced-FF1410.remapped_two_hops.pred",header=F,sep=" ")
colnames(data) <- c("a","b","Prediction","Class")
pred <- prediction(data$Prediction,data$Class)
fm8 <- performance(pred,"f")
bestAccInd <- which.max(fm8@"y.values"[[1]])
zF = paste(zF, paste("NetRate", fm8@"y.values"[[1]][bestAccInd], fm8@"x.values"[[1]][bestAccInd], sep = "\t"), sep = "\r\n")
precrec8 <- performance(pred,"prec", "rec")
roc8 <- performance(pred,"tpr","fpr")
auc8 <- performance(pred,"auc")
aucs[8] = paste("NetRate (AUC = ",sprintf("%.3f",auc8@y.values),")", sep = "")
cut <- optRoc.cut(roc8, pred)
zRoc = paste(zRoc, paste("NetRate", cut[1,1], cut[2,1], cut[3,1], sep = "\t"), sep = "\r\n")
s[8] = paste("NetRate Twitter")

rm(data)
rm(pred)
rm(cut)
rm(bestAccInd)

png(file="Twitter3S2bisFM.png")

par(mar=c(5,5,2,2),xaxs="i",yaxs="i",cex=1.3,cex.axis=1.3,cex.lab=1.3)
plot(fm1,col=1,lty=1,lwd=3,log="x",ylim=c(0,0.3),xlim=c(1e-45,1))
plot(fm2,col=2,lty=1,lwd=3,log="x",add=TRUE)
plot(fm3,col=3,lty=1,lwd=3,log="x",add=TRUE)
plot(fm4,col=4,lty=1,lwd=3,log="x",add=TRUE)
plot(fm5,col=5,lty=1,lwd=3,log="x",add=TRUE)
plot(fm6,col=6,lty=1,lwd=3,log="x",add=TRUE)
plot(fm7,col=7,lty=1,lwd=3,log="x",add=TRUE)
plot(fm8,col=8,lty=3,lwd=1,log="x",pch=22,add=TRUE)
abline(h=seq(0,1,0.1),col="grey",lwd=0.5)
abline(v=seq(0,1,0.1),col="grey",lwd=0.5)
legend(x="bottomleft",c(s[1],s[2],s[3],s[4],s[5],s[6],s[7],s[8]),lwd=c(3,3,3,3,3,3,3,1),lty=c(1,1,1,1,1,1,1,3),col=c(1,2,3,4,5,6,7,8),cex=1)

dev.off()

png(file="Twitter3S2bisPrecRec.png")

par(mar=c(5,5,2,2),xaxs="i",yaxs="i",cex=1.3,cex.axis=1.3,cex.lab=1.3)
plot(precrec1,col=1,lty=1,lwd=3)
plot(precrec2,col=2,lty=1,lwd=3,add=TRUE)
plot(precrec3,col=3,lty=1,lwd=3,add=TRUE)
plot(precrec4,col=4,lty=1,lwd=3,add=TRUE)
plot(precrec5,col=5,lty=1,lwd=3,add=TRUE)
plot(precrec6,col=6,lty=1,lwd=3,add=TRUE)
plot(precrec7,col=7,lty=1,lwd=3,add=TRUE)
plot(precrec8,col=8,lty=3,lwd=1,pch=22,add=TRUE)
abline(h=seq(0,1,0.1),col="grey",lwd=0.5)
abline(v=seq(0,1,0.1),col="grey",lwd=0.5)
legend(x="topleft",c(s[1],s[2],s[3],s[4],s[5],s[6],s[7],s[8]),lwd=c(3,3,3,3,3,3,3,1),lty=c(1,1,1,1,1,1,1,3),col=c(1,2,3,4,5,6,7,8),cex=1)

dev.off()

png(file="Twitter3S2bisRoc.png")

par(mar=c(5,5,2,2),xaxs="i",yaxs="i",cex=1.3,cex.axis=1.3,cex.lab=1.3)
plot(roc1,col=1,lty=1,lwd=3)
plot(roc2,col=2,lty=1,lwd=3,add=TRUE)
plot(roc3,col=3,lty=1,lwd=3,add=TRUE)
plot(roc4,col=4,lty=1,lwd=3,add=TRUE)
plot(roc5,col=5,lty=1,lwd=3,add=TRUE)
plot(roc6,col=6,lty=1,lwd=3,add=TRUE)
plot(roc7,col=7,lty=1,lwd=3,add=TRUE)
plot(roc8,col=8,lty=3,lwd=1,pch=22,add=TRUE)
abline(0,1,col="grey",lty=3,lwd=2)
abline(h=seq(0,1,0.1),col="grey",lwd=0.5)
abline(v=seq(0,1,0.1),col="grey",lwd=0.5)
legend(x="bottomright",c(aucs[1],aucs[2],aucs[3],aucs[4],aucs[5],aucs[6],aucs[7],aucs[8]),lwd=c(3,3,3,3,3,3,3,1),lty=c(1,1,1,1,1,1,1,3),col=c(1,2,3,4,5,6,7,8),cex=1)

dev.off()

cat(zRoc, "\n")
cat(zF, "\n")
